language: elixir
matrix:
  include:
    - otp_release: 20.3
      elixir: 1.7.4
    - otp_release: 21.3
      elixir: 1.7.4
    - otp_release: 21.3
      elixir: 1.8.1
    - otp_release: 22.0
      elixir: 1.8.2
env:
  - MIX_ENV=test
before_script:
  - mix local.hex --force && mix deps.get
script:
  - mix test
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
cache:
  directories:
    - _build
before_cache:
  # should only keep the dialyzer artifacts
  - mix clean
  - mix deps.clean --all
